apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coreserverdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coreserver
    spec:
      containers:
      - name: core-server
        image: atulm.azurecr.io/docker-dotnetcore:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: azurecontainerreg