apiVersion: v1
kind: Service
metadata:
  name: core-server
  labels:
    app: core-server
spec:
  selector:
    app: core-server
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer