apiVersion: v1
kind: Service
metadata:
  name: coreserversvc
  labels:
    version: test
spec:
  selector:
    app: coreserver
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 30062
  type: LoadBalancer